### ISSUE TITLE
Is there any reason why this is not using gulp's programmatic api?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/get-gulp-tasks#1]

**Comment by sindresorhus** [comment]
Yes. I don't remember exactly why, but I don't think there's a good way to extract tasks with the programmatic API and there's also big differences in gulp 3 and 4 that would need to be handled. There would also be problems if the the gulpfile used a loader like Babel. There were also other concerns I don't remember. Spawning will work with any gulp version without any problems.

**Comment by stevemao** [comment]
Would be great if this goes to the docs IMO :)
